name: Build Container

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  noetic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile
          build-args: |
            ROS_DISTRO=noetic
          tags: |
            ghcr.io/${{ github.repository }}:noetic
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=Unity ROS Endpoint (Noetic)
          cache-from: type=gha
          cache-to: type=gha,mode=max